#!/bin/bash
# deploy-multica.sh — 为单个用户部署 Multica（Server + Daemon）。
#
# 复用 Multica 官方 docker-compose.selfhost.yml，不重新打包镜像。
# 在此基础上额外起一个 daemon 容器（含 docker CLI + openclaw/hermes wrapper），
# 通过共享 docker.sock 桥接到该用户已有的 oc-<user> / hermes-hermes-<user> 容器。
#
# 端口规划（与 closeclaw docker_utils.py 对齐）：
#   OpenClaw gateway : 19000+
#   Hermes API       : 20000+
#   Hermes WebUI     : 22000+
#   Multica Frontend : 24000+     (本脚本)
#   Multica Backend  : 26000+     (本脚本，frontend_offset 一致：24010 ↔ 26010)
#
# 用法：
#   ./deploy-multica.sh <username> <port_offset> [service_host]
#
# 例（user-jun 拿到 frontend=24010, backend=26010）：
#   ./deploy-multica.sh user-jun 10
#   ./deploy-multica.sh user-jun 10 oc.l.yuanmu-ai.com
#
# 产物（脚本同级目录下，便于跟随仓库管理）：
#   <script_dir>/multica-deployments/<username>/
#     ├── docker-compose.yml      # postgres + backend + frontend + daemon
#     ├── .env                    # 该用户的密钥/端口/容器名
#     ├── wrappers/
#     │   ├── openclaw            # docker exec -i oc-<user> openclaw
#     │   └── hermes              # docker exec -i hermes-hermes-<user> /opt/hermes/.venv/bin/hermes
#     └── Dockerfile.daemon       # 极简镜像：multica CLI + docker CLI + wrapper

set -euo pipefail

MULTICA_FRONTEND_PORT_BASE=24000
MULTICA_BACKEND_PORT_BASE=26000

USERNAME="${1:?usage: $0 <username> <port_offset> [service_host]}"
PORT_OFFSET="${2:?usage: $0 <username> <port_offset> [service_host]   (e.g. 10 → frontend=24010, backend=26010)}"
SERVICE_HOST="${3:-oc.l.yuanmu-ai.com}"

FRONTEND_PORT=$((MULTICA_FRONTEND_PORT_BASE + PORT_OFFSET))
BACKEND_PORT=$((MULTICA_BACKEND_PORT_BASE + PORT_OFFSET))

# Closeclaw 现有的容器命名约定
OPENCLAW_CONTAINER="oc-${USERNAME}"
HERMES_CONTAINER="hermes-hermes-${USERNAME#user-}"  # hermes 命名去掉 user- 前缀

# 部署根目录（脚本同级 multica-deployments/，每用户一个子目录）
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${SCRIPT_DIR}/multica-deployments/${USERNAME}"
mkdir -p "${ROOT}/wrappers"

# ── 1. 生成 .env ──
JWT_SECRET="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"

cat > "${ROOT}/.env" <<EOF
# Generated by deploy-multica.sh for ${USERNAME}

# Database
POSTGRES_DB=multica
POSTGRES_USER=multica
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PORT=5432

# Server
JWT_SECRET=${JWT_SECRET}
APP_ENV=development
MULTICA_DEV_VERIFICATION_CODE=888888
PORT=8080
FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
SERVICE_HOST=${SERVICE_HOST}

# Multica image channel
MULTICA_IMAGE_TAG=latest
MULTICA_BACKEND_IMAGE=ghcr.io/multica-ai/multica-backend
MULTICA_WEB_IMAGE=ghcr.io/multica-ai/multica-web

# Bridging targets (used by daemon wrappers)
OPENCLAW_CONTAINER=${OPENCLAW_CONTAINER}
HERMES_CONTAINER=${HERMES_CONTAINER}
EOF

# ── 2. 生成 wrapper 脚本 ──
cat > "${ROOT}/wrappers/openclaw" <<'EOF'
#!/bin/bash
# OpenClaw CLI wrapper: forward all args to the user's oc-* container.
# Multica daemon spawns this as if it were openclaw on PATH.
exec docker exec -i "${OPENCLAW_CONTAINER}" openclaw "$@"
EOF
chmod +x "${ROOT}/wrappers/openclaw"

cat > "${ROOT}/wrappers/hermes" <<'EOF'
#!/bin/bash
# Hermes CLI wrapper: forward all args to the user's hermes-* container.
# Hermes binary is not on PATH inside its container; use full venv path.
exec docker exec -i "${HERMES_CONTAINER}" /opt/hermes/.venv/bin/hermes "$@"
EOF
chmod +x "${ROOT}/wrappers/hermes"

# ── 3. 生成 daemon 容器的 Dockerfile ──
# 官方 multica-backend 镜像不包含 daemon CLI 也不包含 docker。我们用
# 一个独立的轻量镜像跑 daemon，挂载 docker.sock + wrappers 即可。
cat > "${ROOT}/Dockerfile.daemon" <<'EOF'
FROM debian:bookworm-slim

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends \
      ca-certificates curl docker.io \
 && curl -fsSL https://raw.githubusercontent.com/multica-ai/multica/main/scripts/install.sh \
        | bash \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Wrappers will be bind-mounted at /usr/local/bin/{openclaw,hermes} so the
# daemon's exec.LookPath finds them. No COPY here — keep image generic.

ENTRYPOINT ["multica", "daemon", "start", "--foreground"]
EOF

# ── 4. 生成 docker-compose.yml ──
# 直接复用官方 selfhost compose 的 postgres + backend + frontend 定义，
# 额外加 daemon 服务和共享的 workspaces volume。
cat > "${ROOT}/docker-compose.yml" <<EOF
# Generated by deploy-multica.sh for ${USERNAME}
# Multica self-host stack + bridged daemon for ${USERNAME}.

name: multica-${USERNAME}

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: \${POSTGRES_DB}
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: \${MULTICA_BACKEND_IMAGE}:\${MULTICA_IMAGE_TAG}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "0.0.0.0:\${BACKEND_PORT}:8080"
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB}?sslmode=disable
      PORT: "8080"
      JWT_SECRET: \${JWT_SECRET}
      APP_ENV: \${APP_ENV}
      MULTICA_DEV_VERIFICATION_CODE: \${MULTICA_DEV_VERIFICATION_CODE}
      MULTICA_APP_URL: http://\${SERVICE_HOST}:\${FRONTEND_PORT}
      FRONTEND_ORIGIN: http://\${SERVICE_HOST}:\${FRONTEND_PORT}
    restart: unless-stopped

  frontend:
    image: \${MULTICA_WEB_IMAGE}:\${MULTICA_IMAGE_TAG}
    depends_on:
      - backend
    ports:
      - "0.0.0.0:\${FRONTEND_PORT}:3000"
    environment:
      HOSTNAME: "0.0.0.0"
    restart: unless-stopped

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    depends_on:
      backend:
        condition: service_started
    environment:
      OPENCLAW_CONTAINER: \${OPENCLAW_CONTAINER}
      HERMES_CONTAINER: \${HERMES_CONTAINER}
      MULTICA_SERVER_URL: ws://backend:8080/ws
      MULTICA_OPENCLAW_PATH: /usr/local/bin/openclaw
      MULTICA_HERMES_PATH: /usr/local/bin/hermes
      MULTICA_WORKSPACES_ROOT: /multica-workspaces
      MULTICA_DAEMON_DEVICE_NAME: ${USERNAME}
    volumes:
      # Bridge to host docker so wrappers can docker exec into sibling containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Wrappers (read-only)
      - ./wrappers/openclaw:/usr/local/bin/openclaw:ro
      - ./wrappers/hermes:/usr/local/bin/hermes:ro
      # Shared workspaces — must mount to the SAME path in oc-* and hermes-* containers
      - multica-workspaces:/multica-workspaces
    restart: unless-stopped

volumes:
  pgdata:
  multica-workspaces:
    name: multica-workspaces-${USERNAME}
EOF

# ── 5. 启动 ──
cd "${ROOT}"
docker compose pull postgres backend frontend
docker compose build daemon
docker compose up -d

echo
echo "✓ Deployed multica for ${USERNAME}"
echo "  Frontend:        https://${SERVICE_HOST}:${FRONTEND_PORT}"
echo "  Backend:         https://${SERVICE_HOST}:${BACKEND_PORT}"
echo "  Login code:      888888 (APP_ENV=development)"
echo "  Compose root:    ${ROOT}"
echo
echo "Next steps:"
echo "  1. Mount volume 'multica-workspaces-${USERNAME}' into ${OPENCLAW_CONTAINER}"
echo "     and ${HERMES_CONTAINER} at /multica-workspaces (requires container recreate)."
echo "  2. Open the frontend, log in with 888888, and you should see"
echo "     the bridged Runtime registered automatically."
echo
echo "Stop:    cd ${ROOT} && docker compose down"
echo "Logs:    cd ${ROOT} && docker compose logs -f daemon"
