#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# DEPRECATED — multica 部署已迁到 closeclaw Multica 模块。
#
# 本脚本生成的栈：
#   - 端口 plain HTTP (24010/26010)，没有 TLS
#   - 起一个独立 daemon 容器走 docker exec 桥接（实际用不上，下游已切到
#     in-container daemon 形态）
#   - 不感知 closeclaw 的 owner / Service 数据
#
# 推荐流程（在 closeclaw 后端跑）：
#   1) 一次性安装：
#        cd ~/closeclaw && uv run python manage.py fetch_multica_binary
#        uv run python manage.py pull_multica_images
#   2) 通过 closeclaw 前端 Multica 页一键起栈、bind oc/hermes（强制同 owner）
#
# 形态差异：closeclaw 起的栈是 4 容器（postgres+backend+frontend+caddy），
# 端口 24443+/26443+（HTTPS-only，用 ssl/cert.{pem,key} 通配证书）。daemon 跑
# 在用户已有的 oc-<user>/hermes-<user> 容器内，登录态走 closeclaw 挂载持久化。
#
# 如果你确定要继续运行本脚本（手工灾备 / 离线场景），加 --i-know-deprecated。
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

if [[ "${1:-}" != "--i-know-deprecated" ]]; then
  echo "DEPRECATED: deploy-multica.sh is superseded by closeclaw Multica UI." >&2
  echo "See header for the new flow. Pass --i-know-deprecated as the first" >&2
  echo "argument if you intentionally want to use this manual script." >&2
  exit 1
fi
shift  # drop --i-know-deprecated so the rest of argv keeps its old positions

MULTICA_FRONTEND_PORT_BASE=24000
MULTICA_BACKEND_PORT_BASE=26000

USERNAME="${1:?usage: $0 <username> <port_offset> [service_host]}"
PORT_OFFSET="${2:?usage: $0 <username> <port_offset> [service_host]   (e.g. 10 → frontend=24010, backend=26010)}"
SERVICE_HOST="${3:-oc.l.yuanmu-ai.com}"

FRONTEND_PORT=$((MULTICA_FRONTEND_PORT_BASE + PORT_OFFSET))
BACKEND_PORT=$((MULTICA_BACKEND_PORT_BASE + PORT_OFFSET))

# Closeclaw 现有的容器命名约定
OPENCLAW_CONTAINER="oc-${USERNAME}"
HERMES_CONTAINER="hermes-hermes-${USERNAME#user-}"  # hermes 命名去掉 user- 前缀

# 部署根目录（脚本同级 multica-deployments/，每用户一个子目录）
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${SCRIPT_DIR}/multica-deployments/${USERNAME}"
mkdir -p "${ROOT}/wrappers"

# ── 1. 生成 .env ──
JWT_SECRET="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"

cat > "${ROOT}/.env" <<EOF
# Generated by deploy-multica.sh for ${USERNAME}

# Database
POSTGRES_DB=multica
POSTGRES_USER=multica
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PORT=5432

# Server
JWT_SECRET=${JWT_SECRET}
APP_ENV=development
MULTICA_DEV_VERIFICATION_CODE=888888
PORT=8080
FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
SERVICE_HOST=${SERVICE_HOST}

# Multica image channel
MULTICA_IMAGE_TAG=latest
MULTICA_BACKEND_IMAGE=ghcr.io/multica-ai/multica-backend
MULTICA_WEB_IMAGE=ghcr.io/multica-ai/multica-web

# Bridging targets (used by daemon wrappers)
OPENCLAW_CONTAINER=${OPENCLAW_CONTAINER}
HERMES_CONTAINER=${HERMES_CONTAINER}
EOF

# ── 2. 生成 wrapper 脚本 ──
cat > "${ROOT}/wrappers/openclaw" <<'EOF'
#!/bin/bash
# OpenClaw CLI wrapper: forward all args to the user's oc-* container.
# Multica daemon spawns this as if it were openclaw on PATH.
exec docker exec -i "${OPENCLAW_CONTAINER}" openclaw "$@"
EOF
chmod +x "${ROOT}/wrappers/openclaw"

cat > "${ROOT}/wrappers/hermes" <<'EOF'
#!/bin/bash
# Hermes CLI wrapper: forward all args to the user's hermes-* container.
# Hermes binary is not on PATH inside its container; use full venv path.
exec docker exec -i "${HERMES_CONTAINER}" /opt/hermes/.venv/bin/hermes "$@"
EOF
chmod +x "${ROOT}/wrappers/hermes"

# ── 3. 生成 daemon 容器的 Dockerfile ──
# 官方 multica-backend 镜像不包含 daemon CLI 也不包含 docker。我们用
# 一个独立的轻量镜像跑 daemon，挂载 docker.sock + wrappers 即可。
cat > "${ROOT}/Dockerfile.daemon" <<'EOF'
FROM debian:bookworm-slim

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends \
      ca-certificates curl docker.io \
 && curl -fsSL https://raw.githubusercontent.com/multica-ai/multica/main/scripts/install.sh \
        | bash \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Wrappers will be bind-mounted at /usr/local/bin/{openclaw,hermes} so the
# daemon's exec.LookPath finds them. No COPY here — keep image generic.

ENTRYPOINT ["multica", "daemon", "start", "--foreground"]
EOF

# ── 4. 生成 docker-compose.yml ──
# 直接复用官方 selfhost compose 的 postgres + backend + frontend 定义，
# 额外加 daemon 服务和共享的 workspaces volume。
cat > "${ROOT}/docker-compose.yml" <<EOF
# Generated by deploy-multica.sh for ${USERNAME}
# Multica self-host stack + bridged daemon for ${USERNAME}.

name: multica-${USERNAME}

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: \${POSTGRES_DB}
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: \${MULTICA_BACKEND_IMAGE}:\${MULTICA_IMAGE_TAG}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "0.0.0.0:\${BACKEND_PORT}:8080"
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB}?sslmode=disable
      PORT: "8080"
      JWT_SECRET: \${JWT_SECRET}
      APP_ENV: \${APP_ENV}
      MULTICA_DEV_VERIFICATION_CODE: \${MULTICA_DEV_VERIFICATION_CODE}
      MULTICA_APP_URL: http://\${SERVICE_HOST}:\${FRONTEND_PORT}
      FRONTEND_ORIGIN: http://\${SERVICE_HOST}:\${FRONTEND_PORT}
    restart: unless-stopped

  frontend:
    image: \${MULTICA_WEB_IMAGE}:\${MULTICA_IMAGE_TAG}
    depends_on:
      - backend
    ports:
      - "0.0.0.0:\${FRONTEND_PORT}:3000"
    environment:
      HOSTNAME: "0.0.0.0"
    restart: unless-stopped

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    depends_on:
      backend:
        condition: service_started
    environment:
      OPENCLAW_CONTAINER: \${OPENCLAW_CONTAINER}
      HERMES_CONTAINER: \${HERMES_CONTAINER}
      MULTICA_SERVER_URL: ws://backend:8080/ws
      MULTICA_OPENCLAW_PATH: /usr/local/bin/openclaw
      MULTICA_HERMES_PATH: /usr/local/bin/hermes
      MULTICA_WORKSPACES_ROOT: /multica-workspaces
      MULTICA_DAEMON_DEVICE_NAME: ${USERNAME}
    volumes:
      # Bridge to host docker so wrappers can docker exec into sibling containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Wrappers (read-only)
      - ./wrappers/openclaw:/usr/local/bin/openclaw:ro
      - ./wrappers/hermes:/usr/local/bin/hermes:ro
      # Shared workspaces — must mount to the SAME path in oc-* and hermes-* containers
      - multica-workspaces:/multica-workspaces
      # Persist daemon auth config across restarts
      - daemon-config:/root/.multica
    restart: unless-stopped

volumes:
  pgdata:
  multica-workspaces:
    name: multica-workspaces-${USERNAME}
  daemon-config:
    name: multica-daemon-config-${USERNAME}
EOF

# ── 5. 启动 ──
cd "${ROOT}"
docker compose build daemon
docker compose up -d

# ── 6. 自动登录 daemon ──
# 等 backend 就绪
echo "Waiting for backend to be ready..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:${BACKEND_PORT}/api/v1/version > /dev/null 2>&1 || \
     curl -sf -o /dev/null -w '%{http_code}' http://localhost:${BACKEND_PORT}/auth/send-code 2>/dev/null | grep -q '4'; then
    break
  fi
  sleep 2
done

# 用 dev verification code 登录拿 JWT
DEV_EMAIL="daemon-${USERNAME}@multica.local"
curl -sf http://localhost:${BACKEND_PORT}/auth/send-code \
  -X POST -H 'Content-Type: application/json' \
  -d "{\"email\":\"${DEV_EMAIL}\"}" > /dev/null

JWT=$(curl -sf http://localhost:${BACKEND_PORT}/auth/verify-code \
  -X POST -H 'Content-Type: application/json' \
  -d "{\"email\":\"${DEV_EMAIL}\",\"code\":\"${MULTICA_DEV_VERIFICATION_CODE:-888888}\"}" \
  | grep -o '"token":"[^"]*"' | cut -d'"' -f4)

if [ -n "${JWT}" ]; then
  # 创建 personal access token
  PAT=$(curl -sf http://localhost:${BACKEND_PORT}/api/tokens \
    -X POST -H 'Content-Type: application/json' \
    -H "Authorization: Bearer ${JWT}" \
    -d '{"name":"daemon-auto"}' \
    | grep -o '"token":"mul_[^"]*"' | cut -d'"' -f4)

  if [ -n "${PAT}" ]; then
    # 用 PAT 登录 daemon（写入 daemon-config volume）
    COMPOSE_PROJECT="multica-${USERNAME}"
    docker run --rm \
      --network "${COMPOSE_PROJECT}_default" \
      -v "multica-daemon-config-${USERNAME}:/root/.multica" \
      -e MULTICA_SERVER_URL=http://backend:8080 \
      --entrypoint multica \
      "${COMPOSE_PROJECT}-daemon" \
      login --token "${PAT}" 2>&1 | head -3

    # 重启 daemon 使其读到新 config
    docker compose restart daemon
    echo "✓ Daemon authenticated automatically"
  else
    echo "⚠ Could not create PAT — run 'multica login' manually in daemon container"
  fi
else
  echo "⚠ Could not get JWT — run 'multica login' manually in daemon container"
fi

echo
echo "✓ Deployed multica for ${USERNAME}"
echo "  Frontend:        http://${SERVICE_HOST}:${FRONTEND_PORT}"
echo "  Backend:         http://${SERVICE_HOST}:${BACKEND_PORT}"
echo "  Login code:      888888 (APP_ENV=development)"
echo "  Compose root:    ${ROOT}"
echo
echo "Next steps:"
echo "  1. Mount volume 'multica-workspaces-${USERNAME}' into ${OPENCLAW_CONTAINER}"
echo "     and ${HERMES_CONTAINER} at /multica-workspaces (requires container recreate)."
echo "  2. Open the frontend, log in with 888888, and you should see"
echo "     the bridged Runtime registered automatically."
echo
echo "Stop:    cd ${ROOT} && docker compose down"
echo "Logs:    cd ${ROOT} && docker compose logs -f daemon"
